### ISSUE TITLE
Error in comment

### ISSUE THREAD

**Issue by Banshaku** [pinobatch/lorom-template#1]
I started to read little by little your sample but this comment is puzzling me a little bit.  Since  it is plb, isn't it for restoring the value from the stack that you saved for the data bank register, not the program bank register? 

https://github.com/pinobatch/lorom-template/blob/967142f73c901584d6970e15a16e5b3215fce972/src/main.s#L45-L46

**Comment by pinobatch** [comment]
I fixed this typo along with a couple others.
